FROM python:3.13-slim-bookworm

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY src test ./

EXPOSE 8000

CMD [ "fastapi", "dev", "src/main.py", "--host", "0.0.0.0" ]